desplegar:
		vagrant up --provider=google

provisionar:
		vagrant provision

clonar:
		fab -H Antkk10@130.211.83.45 -i /Users/antoniomfc90/.ssh/key_gce Clonar

ejecutar:
		fab -H Antkk10@130.211.83.45 -i /Users/antoniomfc90/.ssh/key_gce EjecutarApp

stop:
		fab -H Antkk10@130.211.83.45 -i /Users/antoniomfc90/.ssh/key_gce StopApp

destruir:
		vagrant destroy -f

borrar:
		fab -H Antkk10@130.211.83.45 -i /Users/antoniomfc90/.ssh/key_gce borrar
